export { default as Navbar } from "./Navbar";
export { default as Home } from "./Home";
export { default as Booking } from "./Booking";
export { default as Brand } from "./Brand";
export { default as Category } from "./Category";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as Testimonials } from "./Testimonials";
export { default as TopSelling } from "./TopSelling";
